import type { editor } from 'monaco-editor'

export const oneDarkProTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'abb2bf', background: '282c34' },
    { token: 'heading.1', foreground: 'e06c75', fontStyle: 'bold' },
    { token: 'heading.2', foreground: 'd19a66', fontStyle: 'bold' },
    { token: 'heading.3', foreground: 'e5c07b', fontStyle: 'bold' },
    { token: 'heading.4', foreground: '61afef', fontStyle: 'bold' },
    { token: 'heading.5', foreground: '56b6c2', fontStyle: 'bold' },
    { token: 'heading.6', foreground: '98c379', fontStyle: 'bold' },
    { token: 'emphasis', fontStyle: 'italic', foreground: 'd19a66' },
    { token: 'strong', fontStyle: 'bold', foreground: 'e5c07b' },
    { token: 'strong emphasis', fontStyle: 'bold italic' },
    { token: 'string.link', foreground: '61afef', fontStyle: 'underline' },
    { token: 'string.link.title', foreground: '56b6c2' },
    { token: 'code', foreground: '98c379', background: '2c313c' },
    { token: 'fenced_code', foreground: '98c379', background: '2c313c' },
    { token: 'variable.source', foreground: '98c379' },
    { token: 'keyword', foreground: '5c6370' },
    { token: 'quote', foreground: '7f848e', fontStyle: 'italic' },
    { token: 'meta.separator', foreground: '4b5263' },
    { token: 'punctuation.definition', foreground: '5c6370' },
    { token: 'punctuation.definition.heading', foreground: '5c6370' },
    { token: 'punctuation.definition.list', foreground: '5c6370' },
    { token: 'table', foreground: 'abb2bf' },
    { token: 'table.header', foreground: 'e5c07b', fontStyle: 'bold' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'constant', foreground: 'd19a66' },
    { token: 'string', foreground: '98c379' },
    { token: 'tag', foreground: 'e06c75' },
    { token: 'attribute.name', foreground: 'd19a66' },
    { token: 'attribute.value', foreground: '56b6c2' },
  ],
  colors: {
    'editor.background': '#282c34',
    'editor.foreground': '#abb2bf',
    'editorLineNumber.foreground': '#4b5263',
    'editorLineNumber.activeForeground': '#737a8a',
    'editor.selectionBackground': '#3e4451',
    'editor.inactiveSelectionBackground': '#2c313a',
    'editor.lineHighlightBackground': '#2c313c',
    'editorCursor.foreground': '#528bff',
    'editorWhitespace.foreground': '#3b4048',
    'editorIndentGuide.background': '#3b4048',
    'editorIndentGuide.activeBackground': '#4b5263',
    'editorBracketMatch.background': '#3e4451',
    'editorBracketMatch.border': '#4b5263',
  },
}
