import type { editor } from 'monaco-editor'

export const tokyoNightLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '333333', background: 'fafafa' },
    { token: 'heading.1', foreground: 'd81b60', fontStyle: 'bold' },
    { token: 'heading.2', foreground: 'e91e63', fontStyle: 'bold' },
    { token: 'heading.3', foreground: '9c27b0', fontStyle: 'bold' },
    { token: 'heading.4', foreground: '673ab7', fontStyle: 'bold' },
    { token: 'heading.5', foreground: '3f51b5', fontStyle: 'bold' },
    { token: 'heading.6', foreground: '1e88e5', fontStyle: 'bold' },
    { token: 'emphasis', fontStyle: 'italic', foreground: '555555' },
    { token: 'strong', fontStyle: 'bold', foreground: '222222' },
    { token: 'strong emphasis', fontStyle: 'bold italic' },
    { token: 'string.link', foreground: '00acc1', fontStyle: 'underline' },
    { token: 'string.link.title', foreground: '00bcd4' },
    { token: 'code', foreground: '7cb342', background: 'f1f8e9' },
    { token: 'fenced_code', foreground: '689f38', background: 'f1f8e9' },
    { token: 'variable.source', foreground: '7cb342' },
    { token: 'keyword', foreground: '999999' },
    { token: 'quote', foreground: '78909c', fontStyle: 'italic' },
    { token: 'meta.separator', foreground: 'cccccc' },
    { token: 'punctuation.definition', foreground: 'aaaaaa' },
    { token: 'punctuation.definition.bold', foreground: '999999' },
    { token: 'punctuation.definition.italic', foreground: '999999' },
    { token: 'punctuation.definition.heading', foreground: 'bbbbbb' },
    { token: 'punctuation.definition.list', foreground: 'aaaaaa' },
    { token: 'tag', foreground: 'f06292' },
    { token: 'attribute.name', foreground: 'ff8a65' },
    { token: 'attribute.value', foreground: '4fc3f7' },
    { token: 'table', foreground: '666666' },
    { token: 'table.header', foreground: '222222', fontStyle: 'bold' },
    { token: 'comment', foreground: 'aaaaaa', fontStyle: 'italic' },
    { token: 'constant', foreground: 'ff8a65' },
    { token: 'string', foreground: '00acc1' },
  ],
  colors: {
    'editor.background': '#fafafa',
    'editor.foreground': '#333333',
    'editorLineNumber.foreground': '#cccccc',
    'editorLineNumber.activeForeground': '#888888',
    'editorCursor.foreground': '#d81b60',
    'editor.lineHighlightBackground': '#f5f5f5',
    'editor.findMatchBackground': '#fff59d',
    'editor.findMatchHighlightBackground': '#fff8e1',
    'editorBracketMatch.background': '#e0e0e0',
    'editorBracketMatch.border': '#b0b0b0',
    'editorIndentGuide.background': '#f0f0f0',
    'editorIndentGuide.activeBackground': '#d0d0d0',
    'editorWidget.background': '#ffffff',
    'editorWidget.border': '#e0e0e0',
    'editorSuggestWidget.background': '#ffffff',
    'editorSuggestWidget.selectedBackground': '#60a5fa',
    'editorHoverWidget.background': '#ffffff',
    'editorHoverWidget.border': '#e0e0e0',
    'scrollbarSlider.background': '#e0e0e080',
    'scrollbarSlider.hoverBackground': '#d0d0d080',
    'scrollbarSlider.activeBackground': '#c0c0c080',
    'peekView.border': '#e0e0e0',
    'peekViewEditor.background': '#f9f9f9',
    'peekViewResult.background': '#f5f5f5',
    'editorCodeLens.foreground': '#999999',
    'editorLink.activeForeground': '#00acc1',
    'editorError.foreground': '#e53935',
    'editorWarning.foreground': '#fb8c00',
    'editorInfo.foreground': '#1e88e5',
  },
}
