import type { editor } from 'monaco-editor'

export const tokyoNightTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'a9b1d6', background: '1a1b26' },
    { token: 'heading.1', foreground: 'f7768e', fontStyle: 'bold' },
    { token: 'heading.2', foreground: 'bb9af7', fontStyle: 'bold' },
    { token: 'heading.3', foreground: '9ece6a', fontStyle: 'bold' },
    { token: 'heading.4', foreground: '7aa2f7', fontStyle: 'bold' },
    { token: 'heading.5', foreground: 'bb9af7', fontStyle: 'bold' },
    { token: 'heading.6', foreground: '7dcfff', fontStyle: 'bold' },
    { token: 'emphasis', fontStyle: 'italic', foreground: 'a9b1d6' },
    { token: 'strong', fontStyle: 'bold', foreground: 'c0caf5' },
    { token: 'strong emphasis', fontStyle: 'bold italic' },
    { token: 'string.link', foreground: '7dcfff', fontStyle: 'underline' },
    { token: 'string.link.title', foreground: '7dcfff' },
    { token: 'code', foreground: '9ece6a', background: '16213e' },
    { token: 'fenced_code', foreground: '9ece6a', background: '16213e' },
    { token: 'variable.source', foreground: '9ece6a' },
    { token: 'keyword', foreground: '545c7e' },
    { token: 'quote', foreground: '7aa2f7', fontStyle: 'italic' },
    { token: 'meta.separator', foreground: '2a2f42' },
    { token: 'punctuation.definition', foreground: '545c7e' },
    { token: 'punctuation.definition.bold', foreground: '3b4261' },
    { token: 'punctuation.definition.italic', foreground: '3b4261' },
    { token: 'punctuation.definition.heading', foreground: '2a2f42' },
    { token: 'punctuation.definition.list', foreground: '545c7e' },
    { token: 'tag', foreground: 'f7768e' },
    { token: 'attribute.name', foreground: 'ff9e64' },
    { token: 'attribute.value', foreground: '7aa2f7' },
    { token: 'table', foreground: '86e1a0' },
    { token: 'table.header', foreground: 'c0caf5', fontStyle: 'bold' },
    { token: 'comment', foreground: '545c7e', fontStyle: 'italic' },
    { token: 'constant', foreground: 'ff9e64' },
    { token: 'string', foreground: '7dcfff' },
  ],
  colors: {
    'editor.background': '#1a1b26',
    'editor.foreground': '#a9b1d6',
    'editorLineNumber.foreground': '#3b4261',
    'editorLineNumber.activeForeground': '#737aa2',
    'editorCursor.foreground': '#c0caf5',
    'editor.lineHighlightBackground': '#1f2335',
    'editor.selectionBackground': '#33467c',
    'editor.inactiveSelectionBackground': '#2a2f42',
    'editor.selectionHighlightBackground': '#3f4751',
    'editor.findMatchBackground': '#3f3f0f',
    'editor.findMatchHighlightBackground': '#4f4f1f',
    'editorBracketMatch.background': '#3b4261',
    'editorBracketMatch.border': '#545c7e',
    'editorIndentGuide.background': '#2a2f42',
    'editorIndentGuide.activeBackground': '#3b4261',
    'editorWidget.background': '#16213e',
    'editorWidget.border': '#2a2f42',
    'editorSuggestWidget.background': '#16213e',
    'editorSuggestWidget.selectedBackground': '#3f4751',
    'editorHoverWidget.background': '#16213e',
    'editorHoverWidget.border': '#2a2f42',
    'scrollbarSlider.background': '#3b426180',
    'scrollbarSlider.hoverBackground': '#545c7e80',
    'scrollbarSlider.activeBackground': '#737aa280',
    'peekView.border': '#2a2f42',
    'peekViewEditor.background': '#0f1117',
    'peekViewResult.background': '#16213e',
    'editorCodeLens.foreground': '#545c7e',
    'editorLink.activeForeground': '#7dcfff',
    'editorError.foreground': '#f7768e',
    'editorWarning.foreground': '#ff9e64',
    'editorInfo.foreground': '#7aa2f7',
  },
}
